//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D.U.S.T.S.Identity.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class artistinformation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public artistinformation()
        {
            this.facebooks = new HashSet<facebook>();
            this.instagrams = new HashSet<instagram>();
            this.soundclouds = new HashSet<soundcloud>();
        }
    
        public int artistid { get; set; }
        public string artistname { get; set; }
        public string genre { get; set; }
        public string soundcloud { get; set; }
        public string facebook { get; set; }
        public string instagram { get; set; }
        public string spotify { get; set; }
        public string popularcity { get; set; }
        public string website { get; set; }
        public string email { get; set; }
        public string youtube { get; set; }
        public string twitter { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<facebook> facebooks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<instagram> instagrams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<soundcloud> soundclouds { get; set; }
    }
}
