//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace D.U.S.T.S.Identity.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dustEntities : DbContext
    {
        public dustEntities()
            : base("name=dustEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<artistinformation> artistinformations { get; set; }
        public virtual DbSet<facebook> facebooks { get; set; }
        public virtual DbSet<instagram> instagrams { get; set; }
        public virtual DbSet<soundcloud> soundclouds { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
